# automation.type - {Android, IOS, Web}
# if (mobileBrowserToggle) ? "Execute mobile browser":"Execute mobile app".
automation:
  type: "Web"
  mobileBrowserToggle: true
  appiumServer: "http://127.0.0.1:4723/wd/hub"
  seleniumGridServer: "http://192.168.56.1:4444/wd/hub"

capability:
  android:
    browserName: "NA"
    platformName: "NA"
    platformVersion: "NA"
    deviceName: "NA"
    udid: "NA"
    noReset: true
    fullReset: false
    newCMDTimeout: 60

  ios:
    browserName: "NA"
    platformName: "NA"
    platformVersion: "NA"
    deviceName: "NA"
    udid: "NA"
    noReset: true
    fullReset: false
    newCMDTimeout: 60

# capability.web.browserType - {chrome, firefox} - Take effect with automation.type=Web
# remote to determine whether to run on selenium grid
  web:
    browserType: "chrome"
    remote: false
