# automation.type - {Android, IOS, Web}
automation:
  type: "Android"
  appiumServer: "http://127.0.0.1:4723/wd/hub"
  seleniumGridServer: "http://192.168.56.1:4444/wd/hub"

capability:
  android:
    platformName: "Android"
    platformVersion: "8.0.0"
    deviceName: "GooglePixelAPI26"
    udid: "192.168.56.104:5555"
    noReset: true
    fullReset: false
    newCMDTimeout: 60

  ios:
    platformName: "IOS"
    platformVersion: "ios 12.3"
    deviceName: "iPhone 11 Pro"
    udid: "IdoNotKnow"
    noReset: true
    fullReset: false
    newCMDTimeout: 60

# capability.web.browserType - {chrome, firefox} - Take effect with automation.type=Web
  web:
    browserType: "chrome"
    remote: false
