# Put common beans here, can be overwritten by "Specific environment" or "VM options"

# Profiles: {aosbrowser, aosapp, iosbrowser, iosapp, webbrowser}
spring.profiles.active: aosapp

spring.output.ansi.enabled: always

logging:
  file:
   name: logs/default.log
   path: .
   max-size: 10MB

  pattern:
    console: "%d %clr(%-5level){magenta} %logger : %clr(%msg%n){green}"
    file: "%d %-5level [%thread] %logger : %msg%n"
    rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz

  level:
    com.atcn.bdd.ui.mobile.core: DEBUG
    com.atcn.bdd.ui.mobile.pages: DEBUG
    com.atcn.bdd.ui.mobile.steps: DEBUG
